interactive update operator warning
chronosphereio/calyptia-cli pull request #846
Opened 2024-05-16 09:06 UTC by jasmingacic

# Summary of this proposal

[sc-93553](https://app.shortcut.com/chronosphere/story/93553/calyptia-cli-update-process)

When updating with outdated CLI following Warning message will be printed:

```
# calyptia update operator --kube-namespace calyptia 
Warning: Current version 2.12.0 is less than the latest version 2.12.1
To ensure that the operator functions as intended please install latest version of the CLI, and run "calyptia update operator"
Do you want to proceed with update? (y/N)
n
Error: Aborted
exit status 1
```

Otherwise
```
# calyptia update operator --kube-namespace calyptia 
customresourcedefinition.apiextensions.k8s.io/ingestchecks.core.calyptia.com unchanged
customresourcedefinition.apiextensions.k8s.io/pipelines.core.calyptia.com unchanged
serviceaccount/calyptia-core-controller-manager unchanged
clusterrole.rbac.authorization.k8s.io/calyptia-core-manager-role configured
clusterrole.rbac.authorization.k8s.io/calyptia-core-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/calyptia-core-pod-role unchanged
clusterrole.rbac.authorization.k8s.io/calyptia-core-proxy-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/calyptia-core-manager-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/calyptia-core-proxy-rolebinding unchanged
service/calyptia-core-controller-manager-metrics-service unchanged
deployment.apps/calyptia-core-controller-manager configured
Core operator manager successfully updated to version v2.12.1
```

Update can be forced by passing parameter `--force -f` to the command

2024-05-23 09:33 UTC, patrick-stephens reviewed
We should have an easy test for this locally right?

Also, probably a product call but it would be nice to be able to pin versions and not get this warning as well as overriding the index location for those who won't have internet access. I think we have an option to not check right so that would do that?

2024-05-23 13:27 UTC, jasmingacic commented
> We should have an easy test for this locally right?
> 
> Also, probably a product call but it would be nice to be able to pin versions and not get this warning as well as overriding the index location for those who won't have internet access. I think we have an option to not check right so that would do that?

I can't test unless it is merged into main or released, but we do need a test for that.

Also maybe we should put all notes  into shortcut so Product can chime in

2024-05-23 15:09 UTC, pwhelan approved these changes
LGTM

2024-06-24 14:31 UTC, nicolasparada commented on cmd/operator/update.go
> +				last, _ := semver.NewSemver(laststr)
Please never ignore errors.

2024-06-24 14:31 UTC, nicolasparada commented on cmd/operator/update.go
> +				current, _ := semver.NewSemver(utils.DefaultCoreOperatorDockerImageTag)
Please never ignore errors.

2024-06-24 14:32 UTC, nicolasparada commented on cmd/operator/update.go
> +
```suggestion
```

2024-06-24 14:32 UTC, nicolasparada requested changes
Handle errors.

2024-07-01 09:37 UTC, jasmingacic commented
closing it in favour of future UX overhaul

2024-07-01 09:37 UTC, closed without merging